### ISSUE TITLE
PR: Add support for `eslint-plugin-compat`

### ISSUE THREAD

**Issue by amilajack** [leifoolsen/webpack2-boilerplate#1]
[This eslint plugin](http://github.com/amilajack/eslint-plugin-compat) lints against APIs that are only supported by target browsers 🎉 Would a PR for this be welcome?

**Here's a demo of it in action**

![demo of plugin usage](https://raw.githubusercontent.com/amilajack/eslint-plugin-compat/master/eslint-plugin-compat-demo.gif)

**Comment by leifoolsen** [comment]
Hello @amilajack 
Thank you for suggesting the usage of the eslint-plugin-compat.
The eslint plug-compat will be a really good addition. I've used ES6 Proxy in the logger utility - which is not supported by IE11 and PhantomJS. This linter would probably have detected this.
A PR for this would be great.

Regards

**Comment by leifoolsen** [comment]
Added support for eslint-plugin-compat
