### ISSUE TITLE
babel-node is not meant for production use

### ISSUE THREAD

**Issue by stevula** [leifoolsen/webpack2-boilerplate#3]
It would probably be a good idea to change the `server` script to just use node instead of babel-node. I opened a PR for it but then realized the import/export syntax will not work with the current node release, so I think the server syntax would need to be changed or else transpiled first.

Per Babel docs, the babel-node command is not meant for production use:
https://babeljs.io/docs/usage/cli/#babel-node

>Not meant for production use
You should not be using babel-node in production. It is unnecessarily heavy, with high memory usage due to the cache being stored in memory. You will also always experience a startup performance penalty as the entire app needs to be compiled on the fly.

**Comment by leifoolsen** [comment]
@stevula: Thank you for reporting this. I do not have much experience with Node Express as all our backend services are written in Java (Tomcat and Jetty). We only use Node Express to mock out the API for front end development and testing. Babel-node was the most convenient way to get es6/7 working in Node Express. 

I'll try to look into other options.

**Comment by leifoolsen** [comment]
Changed server script to use `node` instead of `babel-node`. Solved by `require('babel-register')`, to transpile server code on the fly.
